server:
  port: 9095

spring:
  application:
    name: return-learn2

  rabbitmq:
    host: 192.168.110.129
    username: admin
    password: 123456
    port: 5672
    virtual-host: powernode
    publisher-returns: true

my:
  exchangeName: exchange.return.1
  queueName: queue.return.1