server:
  port: 9095

spring:
  application:
    name: exchange-alternate

  rabbitmq:
    host: 192.168.110.129
    username: admin
    password: 123456
    port: 5672
    virtual-host: powernode

my:
  exchangeNormalName: exchange.alter.normal.1
  exchangeAlternateName: exchange.alternate.1
  queueNormalName: queue.alter.normal.1
  queueAlternateName: queue.alternate.1