server:
  port: 9096

spring:
  application:
    name: return-idempotent

  rabbitmq:
    host: 192.168.110.129
    username: admin
    password: 123456
    port: 5672
    virtual-host: powernode
    publisher-confirm-type: correlated #开启发布者确认模式，不管到不到交换机都会回调
    publisher-returns: true #开启发布者的return模式，只有没到队列才会回调
    listener:
      simple:
        acknowledge-mode: manual
  data:
    redis:
      host: 192.168.110.129
      port: 6379
      database: 0 #默认也是0号数据库

#  cache:
#    type: redis
#    cache-names: pc



my:
  exchangeName: exchange.idempotent
  queueName: queue.idempotent