server:
  port: 9093

spring:
  application:
    name: delay-learn1

  rabbitmq:
    host: 192.168.110.129
    username: admin
    password: 123456
    port: 5672
    virtual-host: powernode

my:
  exchangeName: exchange.delay1
  queueNormalName: queue.delay.normal1
  queueDlxName: queue.delay.dlx1