server:
  port: 9095

spring:
  application:
    name: delay-learn1

  rabbitmq:
    host: 192.168.110.129
    username: admin
    password: 123456
    port: 5672
    virtual-host: powernode

my:
  exchangeName: exchange.delay2
  queueNormalName: queue.delay.normal2
  queueDlxName: queue.delay.dlx2