server:
  port: 9090

spring:
  application:
    name: dlx-receive-message-reject
  rabbitmq:
    host: 192.168.110.129
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode
    listener:
        simple:
          acknowledge-mode: manual
